name: 'Terraform GitHub Actions'
on:
  pull_request:
    branches:
      - master

jobs:
  fmt:
    name: 'terraform fmt'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Terraform Format'
        uses: 'clouddrove/github-actions@v9.0.1'
        with:
          actions_subcommand: 'fmt'

  validate:
    name: 'terraform validate'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Configure AZURE Credentials'
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: 'terraform init'
        uses: 'clouddrove/github-actions@v9.0.1'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example

      - name: 'terraform validate'
        uses: 'clouddrove/github-actions@v9.0.1'
        with:
          actions_subcommand: 'validate'
          tf_actions_working_dir: ./_example

  plan:
    name: 'terraform plan'
    env: 
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID   }}
      ARM_CLIENT_SECRETS: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'terraform init'
        uses: 'clouddrove/github-actions@v9.0.1'
        with:
          actions_subcommand: 'init'
          tf_actions_working_dir: ./_example

      - name: 'Configure AZURE Credentials'
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Terraform Plan"
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: "./_example"
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_agent_client_id: ${{ secrets.CLIENT_ID }}
          TF_VAR_agent_client_secret: ${{ secrets.CLIENT_SECRET }}
          TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          TF_VAR_tenant_id: ${{ secrets.TENANT_ID }}

  pre-commit:
    name: 'Pre-Commit'
    needs:
      - fmt
      - plan
      - validate
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4

      - name: 'Install Tflint'
        run: |
          curl https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: 'Pre-Commit 🔎'
        uses: pre-commit/action@v2.0.3
        continue-on-error: true

